openapi: "3.0.0"
info:
   title: InterBet
   version: "1.0.0"

servers:
   - url: https://interbet-api.herokuapp.com
   - url: https://api/v1/interbet.app
   - url: localhost:4000

components:
   securitySchemes:
      bearerAuth:
         name: authentication
         in: header
         type: "apiKey"

   schemas:
      user:
         type: object
         properties:
            id:
               type: integer
               format: int64
            name:
               type: string
            email:
               type: string
            level:
               type: integer
               format: int64
            externalId:
               type: string
            affiliateId:
               type: integer
               format: int64
            teamId:
               type: integer
               format: int64
            picture:
               type: string
            oauth:
               type: string
               enum: ["facebook", "google", "instagram"]
            createdAt:
               type: string
               format: date-time
            updatedAt:
               type: string
               format: date-time
      team:
         type: object
         properties:
            id:
               type: integer
               format: int64
            name:
               type: string
            athleticId:
               type: integer
            abbreviation:
               type: string
            location:
               type: string
            picture:
               type: string
            createdAt:
               type: string
               format: date-time
            updatedAt:
               type: string
               format: date-time
      athletic:
         type: object
         properties:
            id:
               type: integer
               format: int64
            name:
               type: string
            abbreviation:
               type: string
            picture:
               type: string
            createdAt:
               type: string
               format: date-time
            updatedAt:
               type: string
               format: date-time
      events:
         type: object
         properties:
            id:
               type: integer
               format: int64
            name:
               type: string
            description:
               type: string
            title:
               type: string
            location:
               type: string
            createdAt:
               type: string
               format: date-time
            updatedAt:
               type: string
               format: date-time
      notification:
         type: object
         properties:
            id:
               type: integer
               format: int64
            userId:
               type: integer
               format: int64
            title:
               type: string
            message:
               type: string
            unread:
               type: boolean
            createdAt:
               type: string
               format: date-time
            updatedAt:
               type: string
               format: date-time
      wallet:
         type: object
         properties:
            id:
               type: integer
               format: int64
            userId:
               type: integer
               format: int64
            balance:
               type: number
            blocked:
               type: number
            score:
               type: integer
            createdAt:
               type: string
               format: date-time
            updatedAt:
               type: string
               format: date-time
      maintenance:
         type: object
         properties:
            id:
               type: integer
               format: int64
            userId:
               type: integer
               format: int64
            path:
               type: string
            method:
               type: string
               enum: ["GET", "POST", "PUT", "DELETE", "PATCH", "ALL"]
            group:
               type: string
            createdAt:
               type: string
               format: date-time
            updatedAt:
               type: string
               format: date-time
paths:
   /google/oauth:
      post:
         tags:
            - OAuth
         parameters:
            - name: google_authentication
              in: header
              required: true
              schema:
                 type: string
         requestBody:
            content:
               application/json:
                  schema:
                     type: object
                     properties:
                        affiliateId:
                           type: integer
                           format: int64
         responses:
            "200":
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/user"
            "500":
               description: Internal Server Error
               content:
                  application/json:
                     schema:
                        type: object
                        properties:
                           message:
                              type: string
   /facebook/oauth:
      post:
         tags:
            - OAuth
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     type: object
                     properties:
                        accessToken:
                           type: string
                        affiliateId:
                           type: integer
                           format: int64
                        email:
                           type: string
                        picture:
                           type: string
                        name:
                           type: string
                           description: Name of the user from facebook
                        id:
                           type: string
                           description: Facebook ID
         responses:
            "200":
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/user"
   /instagram/oauth:
      post:
         tags:
            - OAuth
         parameters:
            - name: "affiliateId"
              in: query
              schema:
                 type: integer
                 format: int64
            - name: "code"
              description: "Instagram code"
              in: query
              schema:
                 type: string
         responses:
            "200":
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/user"
   /logout:
      post:
         tags:
            - OAuth
         security:
            - bearerAuth: ["authentication"]
         responses:
            "200":
               description: Invalida o token de acesso do usuário
               content:
                  application/json:
                     schema:
                        type: object
                        properties:
                           message:
                              type: string
   /user:
      get:
         tags:
            - User
         security:
            - bearerAuth: ["authentication"]
         responses:
            "200":
               description: Return user details
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/user"
      put:
         tags:
            - User
         security:
            - bearerAuth: ["authentication"]
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     type: object
                     properties:
                        name:
                           type: string
                        teamId:
                           type: integer
                           format: int64
         responses:
            "200":
               description: OK
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/user"
   /wallet:
      get:
         tags:
            - Wallet
         security:
            - bearerAuth: ["authentication"]
         responses:
            "200":
               description: Return wallet details
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/wallet"
   /notifications:
      get:
         tags:
            - Notifications
         security:
            - bearerAuth: ["authentication"]
         responses:
            "200":
               description: Return all notifications
               content:
                  application/json:
                     schema:
                        type: array
                        items:
                           $ref: "#/components/schemas/notification"
   /notifications/{id}/:
      put:
         tags:
            - Notifications
         security:
            - bearerAuth: ["authentication"]
         parameters:
            - name: id
              in: path
              required: true
              schema:
                 type: integer
                 format: int64
         responses:
            "200":
               description: Return all notifications
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/notification"
      delete:
         tags:
            - Notifications
         security:
            - bearerAuth: ["authentication"]
         parameters:
            - name: id
              in: path
              required: true
              schema:
                 type: integer
                 format: int64
         responses:
            "200":
               description: delete successful
            "422":
               description: Invalid ID
            "404":
               description: Not found
            "403":
               description: Unauthorized
   /teams:
      get:
         tags:
            - Teams
         security:
            - bearerAuth: ["authentication"]
         responses:
            "200":
               description: Return teams
               content:
                  application/json:
                     schema:
                        type: array
                        items:
                           $ref: "#/components/schemas/team"
      post:
         tags:
            - Teams
         security:
            - bearerAuth: ["authentication"]
         requestBody:
            required: true
            content:
               multipart/form-data:
                  schema:
                     type: object
                     properties:
                        name:
                           type: string
                        abbreviation:
                           type: string
                        location:
                           type: string
                        athleticId:
                           type: number
                        picture:
                           type: string
                           format: binary
                           description: File to upload

         responses:
            "200":
               description: Return teams
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/team"
   /teams/{search}/:
      get:
         tags:
            - Teams
         security:
            - bearerAuth: ["authentication"]
         parameters:
            - name: name
              in: path
              required: true
              schema:
                 type: string
         responses:
            "200":
               description: Return all teams by like the name
               content:
                  application/json:
                     schema:
                        type: array
                        items:
                           $ref: "#/components/schemas/team"
   /athletics:
      get:
         tags:
            - Athletics
         security:
            - bearerAuth: ["authentication"]
         responses:
            "200":
               description: Return all athletics
               content:
                  application/json:
                     schema:
                        type: array
                        items:
                           $ref: "#/components/schemas/athletic"
      post:
         tags:
            - Athletics
         security:
            - bearerAuth: ["authentication"]
         requestBody:
            required: true
            content:
               multipart/form-data:
                  schema:
                     type: object
                     properties:
                        picture:
                           type: string
                           format: binary
                           description: File to upload
                        name:
                           type: string
                           description: Name of the athletic
                        abbreviation:
                           type: string
                           description: Abbreviation of the athletic
         responses:
            "200":
               description: Return the created athletic
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/athletic"
   /athletics/{search}/:
      get:
         tags:
            - Athletics
         security:
            - bearerAuth: ["authentication"]
         parameters:
            - name: name
              in: path
              required: true
              schema:
                 type: string
         responses:
            "200":
               description: Return all athletics by like the name
               content:
                  application/json:
                     schema:
                        type: array
                        items:
                           $ref: "#/components/schemas/athletic"
   /events:
      get:
         tags:
            - Events
         security:
            - bearerAuth: ["authentication"]
         responses:
            "200":
               description: Return all events
               content:
                  application/json:
                     schema:
                        type: array
                        items:
                           $ref: "#/components/schemas/events"
      post:
         tags:
            - Events
         security:
            - bearerAuth: ["authentication"]
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     type: object
                     properties:
                        name:
                           type: string
                           description: Name of the event
                        description:
                           type: string
                           description: Description of the event
                        title:
                           type: string
                           description: Title of the event
                        location:
                           type: string
                           description: Location of the event
         responses:
            "200":
               description: Return the created event
               content:
                  application/json:
                     schema:
                        $ref: "#/components/schemas/event"
   /maintenances/{group}/:
      get:
         tags:
            - Maintenances
         security:
            - bearerAuth: ["authentication"]
         parameters:
            - name: group
              in: path
              required: true
              schema:
                 type: integer
                 format: int64
                 description: Group to filter maintenances
         responses:
            "200":
               description: "Return the array os search maintenances"
   /maintenances:
      get:
         tags:
            - Maintenances
         security:
            - bearerAuth: ["authentication"]
         responses:
            "200":
               description: Return all maintenances
               content:
                  application/json:
                     schema:
                        type: array
                        items:
                           $ref: "#/components/schemas/maintenance"
      post:
         tags:
            - Maintenances
         security:
            - bearerAuth: ["authentication"]
         requestBody:
            required: true
            content:
               application/json:
                  schema:
                     type: object
                     properties:
                        userId:
                           type: integer
                           format: int64
                        path:
                           type: string
                        group:
                           type: string
                        method:
                           type: string
                           enum: ["GET", "POST", "PUT", "DELETE", "ALL", "PATCH"]
         responses:
            "201":
               description: "Created successfully"
   /maintenances/{id}/:
      delete:
         tags:
            - Maintenances
         security:
            - bearerAuth: ["authentication"]
         parameters:
            - name: id
              in: path
              required: true
              schema:
                 type: integer
                 format: int64
         responses:
            "200":
               description: "Deleted successfully"

